Allow only partially mapped methods
ParchmentMC/Librarian pull request #8
Opened 2022-04-22 17:01 UTC by noeppi-noeppi

This fixes #7 by implementing a mapper from JVM indices to source indices (as used by the SRG since 1.17). For that, it parses the method descriptor and the `is_static` metadata obtained from the SRG.

I have tested the changes in this PR with parchment `2022.03.13` on Forge `40.0.48`. I looked a several static and non-static methods that contained `long` and `double` and they were mapped correctly. Also in `FormattedCharSink` the two parameters that have names in parchment for that version got mapped now.

2022-04-22 18:15 UTC, SizableShrimp requested changes

2022-04-22 18:15 UTC, SizableShrimp commented on src/main/java/org/parchmentmc/librarian/forgegradle/ParchmentChannelProvider.java
> +    }
I feel like I've seen this somewhere. Is this copied from another project somewhere? Maybe just my mind playing tricks on me.

2022-04-22 18:15 UTC, SizableShrimp commented on src/main/java/org/parchmentmc/librarian/forgegradle/ParchmentChannelProvider.java
> +    public static int jvmToSrg(IMethod srgMethod, int jvmIndex) {
This doesn't need to be public; I would prefer protected.

2022-04-22 18:15 UTC, SizableShrimp commented on src/main/java/org/parchmentmc/librarian/forgegradle/ParchmentChannelProvider.java
> +        // Arrays are references wit only regular size, no matter if it's a long or double array
Typo: "wit" -> "with"

I would prefer something like "Arrays are references always with a size of one regardless of the array type"

2022-04-22 18:15 UTC, SizableShrimp commented on src/main/java/org/parchmentmc/librarian/forgegradle/ParchmentChannelProvider.java
> + * Copyright (C) 2022 ParchmentMC
This is best not to update. The formatter will just overwrite this change. I will probably update the license when I next need to push something, but best to do all at one time, and the year is really minor.

2022-04-22 18:15 UTC, SizableShrimp commented on src/main/java/org/parchmentmc/librarian/forgegradle/ParchmentChannelProvider.java
> +        if (isOfficialExport && srgMethod == null)
This makes more sense to me if the original `constructorId == null` check was kept.

2022-04-22 18:54 UTC, noeppi-noeppi commented on src/main/java/org/parchmentmc/librarian/forgegradle/ParchmentChannelProvider.java
> +    }
I used a similar approach in SourceTransform. And I think the first version of ModGradle contained some code for the same thing. However I wrote that up from scratch.

2022-04-22 19:02 UTC, noeppi-noeppi commented on src/main/java/org/parchmentmc/librarian/forgegradle/ParchmentChannelProvider.java
> +        if (isOfficialExport && srgMethod == null)
I don't get, what you mean. If I understand it correctly, either `srgMethod` or `constructorId` will be `null`. So if that checked only for the `constructorId` being null, it would cause a `NullPointerException` on line 236. Checking for `srgMethod == null && constructorId == null` would always be `false` and `srgMethod == null || constructorId == null` would always be `true`.

2022-04-22 19:35 UTC, SizableShrimp commented on src/main/java/org/parchmentmc/librarian/forgegradle/ParchmentChannelProvider.java
> +        if (isOfficialExport && srgMethod == null)
After looking at it again, this makes sense to me. I was originally thinking that just the last boolean expression should be deleted, but that would cause all methods on official exports to fail to be mapped. In this way, it would skip a potential NPE that is only possible because of your changed code path.

2022-04-22 19:39 UTC, SizableShrimp requested changes

2022-04-22 19:39 UTC, SizableShrimp commented on src/main/java/org/parchmentmc/librarian/forgegradle/ParchmentChannelProvider.java
> +    // Converts a JVM parameter index (as used by the parchment export) to a SRG parameter index.
This would be better as a javadoc comment.

2022-04-22 19:39 UTC, SizableShrimp commented on src/main/java/org/parchmentmc/librarian/forgegradle/ParchmentChannelProvider.java
> +    protected int jvmToSrg(IMethod srgMethod, int jvmIndex) {
I would prefer a better name for this that is more descriptive. `convertJvmIndexToSrgIndex` maybe? Something that specifies they are indices.

2022-04-22 19:39 UTC, SizableShrimp commented on src/main/java/org/parchmentmc/librarian/forgegradle/ParchmentChannelProvider.java
> +        args = args.replaceAll("\\[+.", "L");
I doubt `L;` with nothing inbetween is valid, so the modifier should be `.+?`. Additionally, please make both of these `replaceAll` calls use precompiled protected static final patterns.

2022-04-22 19:39 UTC, SizableShrimp commented on src/main/java/org/parchmentmc/librarian/forgegradle/ParchmentChannelProvider.java
> +            if (srgIdx < args.length() && args.charAt(srgIdx) == 'J' || args.charAt(srgIdx) == 'D') {
I don't think this logic is correctly. The && has a higher priority than ||, so the `== 'D'` could cause an IndexOutOfBoundsException. The `||` check should be wrapped in parentheses.

2022-04-24 00:53 UTC, SizableShrimp approved these changes
This looks good to me. One last thing though. The `codever` attribute in the hash store can be bumped to force all old generated mappings to be redone. This would mean that the partially mapped methods would be immediately applied once Librarian is updated in a user's workspace. But there are so few methods that are partially mapped (afaik) that I don't think this is worth it to bump. What are your thoughts?

2022-04-24 08:05 UTC, noeppi-noeppi commented
There are really only a few methods, and usually you won't notice that some parameters are missing. So yeah, I agree, it is not really necessary to update `codever`.

2022-06-29 05:21 UTC, merged